# Generated by Django 4.2.2 on 2023-06-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_image_dicount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dicount',
            new_name='Discount',
        ),
    ]
